# Author: Vincenzo Merola <vincenzo.merola2@unina.it>
# Description:
#   	This Makefile uses Vitis compiler to simulate and synthesize HLS kernel.

# Tools
VITIS_HLS = vitis-run --mode hls
VPP = v++
VFLAGS = -c --mode hls

# Other flags
CPPFLAGS = -DUINT8

# Commands
CSIM = ${VITIS_HLS} --csim
COSIM = ${VITIS_HLS} --cosim
SYN = ${VPP} ${VFLAGS}
PACK = ${VITIS_HLS} --package
IP = ${DIR}_hls

# Config file
CONFIG_GILE = src/hls_config.cfg
CONFIG = --config ${CONFIG_GILE}

# Build directory
DIR = attention
WORK_DIR = --work_dir ${DIR}


# Targets
# The configuration HLS file is generated by a reference by adding some needed flags
gen_config:
	@echo "Writing config file..."
	@cp -f src/hls_config_base.cfg src/hls_config.cfg
	@echo "" >> src/hls_config.cfg
	@echo "cflags=${CPPFLAGS}" >> src/hls_config.cfg
	@echo "csim.cflags=${CPPFLAGS}" >> src/hls_config.cfg
	@echo "syn.cflags=${CPPFLAGS}" >> src/hls_config.cfg
	@echo

csim: gen_config
	@echo "C-Simulation starting..."
	${CSIM} ${CONFIG} ${WORK_DIR}
	@echo

syn: gen_config
	@echo "Synthesis starting..."
	${SYN} ${CONFIG} ${WORK_DIR}
	@echo

cosim: syn
	@echo "Cosimulation starting ..."
	${COSIM} ${CONFIG} ${WORK_DIR}
	@echo

package: syn
	@echo "Packaging IP..."
	${PACK} ${CONFIG} ${WORK_DIR}
	@echo


# Clean target
clean:
	@echo "Cleaning..."
	rm -f ${IP}.zip

	rm -rf ${DIR}
	rm -f xcd.log
	rm -rf .Xil

	rm -f src/hls_config.cfg


.PHONY: csim syn cosim package clean
